AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Apache Struts API - com.pruebaJenkins::my-project-jenkins
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyProjectJenkinsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.serverless.proxy.struts.StrutsLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyProjectJenkinsApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyProjectJenkinsApi
